version: "3.3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 8080:8080
    command: bash -c "uvicorn app.main:app --workers 1 --host 0.0.0.0 --port 8080 --reload"
    environment:
      - LOGGER=uvicorn