[tool.isort]
profile = "black"
force_sort_within_sections = true
length_sort = true
known_first_party = ["app", "pubsub"]
forced_separate = ["app.config", "app.db", "app.daos", "app.enums", "app.internal", "app.middleware", "app.models", "app.routers", "app.schemas", "."]