[tool.isort]
profile = "black"
force_sort_within_sections = true
length_sort = true
known_first_party = ["app"]
forced_separate = ["app.songGPT", "app.routers", "app.schemas", "app.daos", "app.firebase"]